// Generated by tool/configure_features.py. Do not edit by hand.
import '../platform/feature_module.dart';
import '../features/pets/module.dart';
import '../features/care/module.dart';
import '../features/health/module.dart';
import '../features/community/module.dart';
import '../features/store/module.dart';
import '../features/budget/module.dart';
import '../features/basket/module.dart';
import '../features/firstdays/module.dart';
import '../features/findvet/module.dart';

const builtInFeatureIds = <String>{
  'access',
  'basket',
  'budget',
  'care',
  'community',
  'findvet',
  'firstdays',
  'health',
  'pets',
  'store',
};
final builtInFeatureModules = <FeatureModule>[
  petsModule,
  careModule,
  healthModule,
  communityModule,
  storeModule,
  budgetModule,
  basketModule,
  firstDaysModule,
  findVetModule,
  const FeatureModule(id: 'access'),
];
