"""Generate the build composition; omitted modules have no UI import edges.
Usage: python tool/configure_features.py --modules pets,care,store,basket
Restore the complete app with: python tool/configure_features.py
"""
from pathlib import Path
import argparse
root=Path(__file__).resolve().parents[1]
catalog={'pets':'petsModule','care':'careModule','health':'healthModule','community':'communityModule',
 'store':'storeModule','budget':'budgetModule','basket':'basketModule','firstdays':'firstDaysModule','findvet':'findVetModule'}
parser=argparse.ArgumentParser();parser.add_argument('--modules',default=','.join(catalog))
requested={x.strip() for x in parser.parse_args().modules.split(',') if x.strip()}
unknown=requested-set(catalog)-{'basket','access'}
if unknown:parser.error('Unknown modules: '+','.join(sorted(unknown)))
requested.add('access')
lines=['// Generated by tool/configure_features.py. Do not edit by hand.',"import '../platform/feature_module.dart';"]
for name in catalog:
 if name in requested:lines.append(f"import '../features/{name}/module.dart';")
lines += ['','const builtInFeatureIds = <String>{'+','.join(repr(n) for n in sorted(requested))+'};',
 'final builtInFeatureModules = <FeatureModule>[']
for name,var in catalog.items():
 if name in requested:lines.append('  '+var+',')
lines+=['  const FeatureModule(id: \'access\'),','];','']
(root/'lib/composition/modules.g.dart').write_text('\n'.join(lines),encoding='utf-8')
